services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/app/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    profiles:
      - tools
      - quality
    ports:
      - '9000:9000'
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - app-network

  diun:
    image: crazymax/diun:4.30.0
    command: serve --config /docker/dev/diun/diun.yml
    profiles:
      - tools
      - monitoring
    volumes:
      - './docker/dev/diun:/docker/dev/diun'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './docker/dev/diun/data:/data'
    environment:
      - TZ=Europe/Berlin
      - 'LOG_LEVEL=info'
      - 'LOG_JSON=false'
    restart: always
    networks:
      - app-network

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
