name: 'Setup Node.js and Dependencies'
description: 'Composite action to setup Node.js and install npm dependencies with caching'
author: 'Security Team'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  audit:
    description: 'Run npm audit during install'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.audit }}" = "true" ]; then
          npm ci
        else
          npm ci --audit=false
        fi
